language: php

php:
  - 5.4
  - 5.6
  - hhvm

env:
  - DB=memory
  - DB=mysql
  - DB=psql
  - DB=sqlite

matrix:
  exclude:
    # postgre is unsupported on hhvm
    - php: hhvm
      env: DB=psql

before_install:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar

before_script:
  - composer self-update
  - composer install
  - if [[ "$DB" == "psql" ]]; then psql -c 'create database phergie_plugin_tell_test;' -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phergie_plugin_tell_test;" -uroot; fi

script:
  - ./vendor/bin/phpunit --configuration phpunit_$DB.xml --coverage-text
  - php php-cs-fixer.phar fix -v --dry-run
